-- This is an auto-generated migration file.
-- Please do not edit this file manually.

ALTER TABLE `BarangMasuk` ADD COLUMN `masa_exp` DATETIME NULL;
ALTER TABLE `BarangKeluar` ADD COLUMN `masa_exp` DATETIME NULL;
